server.name: "kibana"
server.host: "0.0.0.0"
#server.ssl.enabled: true
#server.ssl.certificate: /usr/share/kibana/config/certs/kibana.crt
#server.ssl.key: /usr/share/kibana/config/certs/kibana.key
#elasticsearch.ssl.certificateAuthorities: ["/usr/share/kibana/config/certs/ca.crt"]
#elasticsearch.ssl.verificationMode: none
elasticsearch.hosts: ["http://192.168.56.100:9200"]
elasticsearch.username: kibana_system
elasticsearch.password: xiaowu
elasticsearch.requestTimeout: 60000
xpack.reporting.encryptionKey: fd7c75cf-6abd-4704-a614-10a8679d64e7
#monitoring.ui.enabled: true
#monitoring.ui.container.logstash.enabled: true
xpack.reporting.capture.browser.chromium.disableSandbox: false
#server.publicBaseUrl: http://0.0.0.0:5601
xpack.encryptedSavedObjects.encryptionKey: 554d5cab-b336-eb0a-e128-6c5012dcc330
i18n.locale: "zh-CN"
